language: ruby
rvm:
  - 2.3.3
sudo: false

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer _site --check-html

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
